### ISSUE TITLE
feat req: Allow changing direction of ProgressBarComponent

### ISSUE THREAD

**Issue by aapoalas** [Im-Beast/deno_tui#16]
**What this feature is meaning to achieve** ProgressBarComponent currently supports horizontal and vertical modes. It would be nice if it could also support horizontal-reverse and vertical-reverse modes. Alternate names would be `rtl`, `ltr`, `ttb`, `btt`.

**Solution** Invert min-max-value to draw scale calculations.

**Describe alternatives you've considered** I could manually invert my own inputs to the component, but due to how I'm streaming in values for these it would be a bit of a pain to do.

**Comment by ElectronicsArchiver** [comment]
This seems more sensible no?

```js
{
  direction : 'vertical' ,
  reverse : true
}
```

**Comment by Im-Beast** [comment]
When 2.0 launches this will be possible.
`ProgressBar` in version 2.0 has two separate properties: `orientation` and `direction`.
`orientation` specifies whether progressbar should be horizontal or vertical and `direction` specifies the `direction` of progress flow – `"normal"` or `"reversed"`
