### ISSUE TITLE
Editorconfig

### ISSUE THREAD

**Issue by ElectronicsArchiver** [Im-Beast/deno_tui#18]
Have you considered adding an **[Editorconfig]** file to the repository?

I would recommend the following settings:

```editorconfig

root = true

[*]
insert_final_newline = true
end_of_line = lf


[*.{md,ts,jsonc}]
indent_style = space
indent_size = 4
charset = utf-8

```

[Editorconfig]: https://editorconfig.org/

**Comment by Im-Beast** [comment]
[deno_fmt](https://deno.land/manual@v1.28.0/tools/formatter) is used for formatting the code.

**Comment by ElectronicsArchiver** [comment]
> [deno_fmt](https://deno.land/manual@v1.28.0/tools/formatter) is used for formatting the code.

I'm not talking about post formatting though,
editorconfig gives most editors simple hints
to follow, so it doesn't insert tabs instead
of spaces ( for example ) to begin with or
keeps the correct amount for each key press.

**Comment by Im-Beast** [comment]
it's called formatting.

**Comment by ElectronicsArchiver** [comment]
Calling denos formatting command is **Post**-formatting, while 
an editorconfig file is **Pre**-formatting in this context.

One adjusts the content after the fact, the other 
prevents things from happening in the first place.

Both are valid and can be used together.
