### ISSUE TITLE
bug: Input rectangle does not exist

### ISSUE THREAD

**Issue by load1n9** [Im-Beast/deno_tui#27]
**Bug description** tui.drawnObjects.background!.rectangle is not defined 

**Expected behavior** tui.drawnObjects.background!.rectangle should be defined

**Screenshots** 
![image](https://github.com/Im-Beast/deno_tui/assets/49134864/65915dc3-564b-4ff6-80a0-6eb2ac07c4e1)

**Information**

- OS: Windows 
- Deno version: 1.36.0+433ecc9

**Comment by Im-Beast** [comment]
You should use `tui.rectangle` instead.

The thing I asked you to report was about input not working very well with layouts, that's because input has to be 1 line high, I will need to think about changing it. Sorry for miscommunication.
