### ISSUE TITLE
bug: Label doesnt show text properly

### ISSUE THREAD

**Issue by DNAScanner** [Im-Beast/deno_tui#31]
**Bug description** I tried using the label for displaying a 16x16 / 16x32 texture made up of ansi codes and spaces. Only the first column is shown, the rest isnt shown at all.

**Expected behavior** Show all columns

**Reproduction**
```ts
new Label({
	parent: tui,
	rectangle: {
		column: 0,
		row: 0,
	},
	text: textures.stone,
	theme: {
		base(text) {
			return text;
		},
	},
	zIndex: 1,
});
```

textures.stone is the same as in the attached file

**Screenshots**
![image](https://github.com/Im-Beast/deno_tui/assets/75182303/82970b36-0908-46c1-81b9-4cabe9d8397f)
![image](https://github.com/Im-Beast/deno_tui/assets/75182303/34551808-adc1-4a0a-9b12-0865d600f82c)

Text:
[stone.txt / textures.stone](https://github.com/Im-Beast/deno_tui/files/12564229/stone.txt)

**Information (please complete)**

- OS: Windows_NT DNAScanner 6.2 9200 x86_64 MS/Windows
- Deno version:
> deno 1.36.4 (release, x86_64-pc-windows-msvc)
> v8 11.6.189.12
> typescript 5.1.6

**Comment by Im-Beast** [comment]
Fixed in `2.1.2` (https://github.com/Im-Beast/deno_tui/commit/9ffffad911f3ed3be9a54a9984435f20859140bf)
