### ISSUE TITLE
Potential license issue

### ISSUE THREAD

**Issue by proehlen** [Im-Beast/deno_tui#32]
Hi, I appreciate the work you've put into this project and that you've made it publicly available. However, I notice that 65 or so of the files in your project contain " All rights reserved. MIT license." in the header. 

https://github.com/Im-Beast/deno_tui/blob/main/src/components/table.ts

It's my understanding that the use of the phrase "All rights reserved" is, at best, redundant or, at worst, contradictory with the MIT license:

https://opensource.stackexchange.com/a/4403

https://g.co/bard/share/3e4c8688afbf

IANAL and I assumed you copied this usage from another project but I can't unfortunately use your code while the license is seemingly ambiguous. Regardless of whether you decide to change it or not, thanks for considering this issue.

**Comment by Im-Beast** [comment]
I'll gladly change that, I'm pretty sure I just copied that phrase from somewhere, thanks for noticing!

**Comment by Im-Beast** [comment]
It seems like `deno_std` uses the same phrase, you probably should report an issue about it there, e.g. https://github.com/denoland/deno_std/blob/5700c3deeba37616d34ea389addf42e163897df9/csv/mod.ts#L1

**Comment by proehlen** [comment]
> It seems like `deno_std` uses the same phrase, you should probably report an issue about it there too, e.g. https://github.com/denoland/deno_std/blob/5700c3deeba37616d34ea389addf42e163897df9/csv/mod.ts#L1

Will do and thanks for taking the time to look at this.
