### ISSUE TITLE
Demo on terminals with light color schemes = Bad color contrast

### ISSUE THREAD

**Issue by prettykool** [Im-Beast/deno_tui#7]
So, there's a bit of an issue with the demo - In regards to how it functions on terminals with light color schemes(IE, black on white, and similar).
See the attachment for the demo in action - Only the terminal on the bottom right has a dark color scheme enabled.
![image](https://user-images.githubusercontent.com/79608594/183488487-d75b5511-eb83-4ecb-9e22-cde986ad4030.png)
I believe the main culprit behind this is how the demo explicitly specifies that the background should be a dark grey - Which wouldn't be a problem in and of itself, if not for the fact it doesn't *also* specify that the text be something that contrasts better with it - Like a shade of white, for instance. This causes terminals to fallback to the default color scheme for the foreground text - Which, obviously, is problematic for lighter terminals.

**Comment by Im-Beast** [comment]
Simple fix for that is to add white text color style

**Comment by Im-Beast** [comment]
Issue got fixed via commit #66014b, closing.
